name: Sync Weather Data

on:
  workflow_dispatch:

jobs:
  sync-weather:
    runs-on: ubuntu-latest
    steps:
      - name: Call Weather API
        run: |
          curl --fail --show-error -X GET "https://${{ vars.VERCEL_URL || 'lebihdari.pot' }}/api/weather" \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}"
